### ISSUE TITLE
Add deprecation notice

### ISSUE THREAD

**Issue by AndreiMotinga** [BrightcoveOS/Ruby-MAPI-Wrapper#19]
If I understand it correctly, the API this was built for is deprecated. 
In which case it probably makes sense to add a warning to the Readme.

**Comment by czarneckid** [comment]
There is at the top:

"WARNING: The Media API is deprecated and should not be used for new projects. More information."

**Comment by AndreiMotinga** [comment]
@czarneckid 
my apologies.

**Comment by czarneckid** [comment]
No worries. I bumped up the notice in the README to the top so it's a bit more prominent.
